const assert=require('node:assert/strict');
const {mapTimelineResultToRecruiterViewModel:map}=require('./viewmodel');
const event={id:'e',type:'EMPLOYMENT',title:'Engineer',org:'Company',status:'CONFIRMED',precision:'year',date_label:'2018 – 2020'};
let view=map({timeline:[event],gaps:[{state:'INSUFFICIENT_EVIDENCE'}],item_state:{e:{reviewed:true,hidden:true}},notes:[{author:'Recruiter',text:'Verify dates'}]});
assert.equal(view.events[0].dateLabel,'2018 – 2020');
assert.equal(view.events[0].uncertain,false);
assert.equal(view.visibleEvents.length,0);
assert.equal(view.hiddenItems.length,1);
assert.equal(view.hiddenItems[0].reviewed,true);
assert.match(view.assessment,/Insufficient dated evidence/);
assert.equal(view.notes[0].author,'Recruiter');
view=map({timeline:[{...event,precision:'month'}],gaps:[{id:'g',state:'POTENTIAL_GAP',months:2,start_label:'Aug 2018',end_label:'Sep 2018'},{state:'NO_GAP_DETECTED'}]});
assert.equal(view.periods.length,1);
assert.match(view.periods[0].label,/2 months/);
assert.equal(map({unresolved_events:[{id:'u',type:'EMPLOYMENT'}]}).events[0].dateLabel,'Dates not stated');
assert.equal(map({unresolved_events:[{type:'PROJECT'}]}).events.length,0);
console.log('View model assertions passed');

view=map({timeline:[{...event,status:'CONFIRMED',precision:'month',org:'Quess Corp Ltd',date_label:'June2024 –April,2025'}],unresolved_events:[{id:'edu',type:'EDUCATION',title:'Master Software Engineering',status:'UNRESOLVED'}]});
assert.equal(view.events.filter(e=>e.uncertain).length,0);
view=map({timeline:[{...event,id:'before',org:'Saksoft Ltd'},{...event,id:'after',org:'Quess Corp Ltd'}],gaps:[{id:'g',months:3,state:'POTENTIAL_GAP',start:'2024-03',end:'2024-05',evidence:{event_before:'before',event_after:'after',coverage_scope:'employment'}}]});
assert.equal(view.periods[0].between,'Saksoft Ltd → Quess Corp Ltd');
assert.equal(view.periods[0].scope,'employment');

const {formatEvaluation}=require('./viewmodel');
assert.match(formatEvaluation({overall_accuracy:.875,cases:10,generated_at:'2026-09-22T10:00:00Z'}),/87.5%.*10 labeled test cases.*2026-09-22/);
assert.match(formatEvaluation({overall_accuracy:1,cases:10}),/not this resume’s verified accuracy/);
for(const score of [null,undefined,NaN,Infinity,-1,1.1,'0.99'])assert.match(formatEvaluation({overall_accuracy:score,cases:10}),/unavailable/);
assert.match(formatEvaluation({overall_accuracy:1,cases:0}),/unavailable/);
const dtoClean = { timeline: [{ confidence: 0.95 }, { confidence: 0.95 }] };
const dtoAmbiguous = { timeline: [{ confidence: 0.85, status: 'AMBIGUOUS' }, { confidence: 0.80 }], unresolved_events: [{}] };
const accClean = formatEvaluation(null, dtoClean);
const accAmb = formatEvaluation(null, dtoAmbiguous);
assert.match(accClean, /has not been independently measured/);
assert.equal(accClean,accAmb);
assert.match(formatEvaluation({overall_accuracy:1,calibrated_accuracy:.9,cases:10},dtoClean),/100%/);
